---
name: deploy
'on':
  push:
  pull_request:
    branches:
      - '**:**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install library
        run: poetry install --no-interaction

      - name: Push to Gemfury
        run: |
          source .venv/bin/activate
          python setup.py sdist
          echo find ./dist -name '*.tar.gz'
          curl -F package=@dist/django-tenant-users-0.1.tar.gz https://${{ secrets.GEM_FURY_TOKEN }}@push.fury.io/vaunorage/
